version: '3.7'

networks:
  app:
    driver: bridge

services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - app

  postgresql:
    image: postgres:latest
    container_name: postgresql-container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app

