storage_path: "./storage/storage.db"
http_server: 
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
database:
  username: "user"
  password: "password"
  host: "postgresql"
  port: 5432
  database_name: "postgres"
  