GET http://localhost:8080/posts?page=1&page_size=15 HTTP/1.1

###

GET http://localhost:3000/posts?page=2 HTTP/1.1

###

GET http://localhost:3000/posts/22 HTTP/1.1


###

GET http://localhost:8080/posts/another author HTTP/1.1


###

POST http://localhost:8080/posts HTTP/1.1
content-type: application/json

{
    "title": "some",
    "content": "any content",
    "author": "author"
}

###

PUT http://localhost:8080/posts HTTP/1.1
content-type: application/json

{
    "id": 4,
    "title": "4",
    "content": "updated content",
    "author": "updated author"
}

###

DELETE http://localhost:8080/posts/23 HTTP/1.1
